### ISSUE TITLE
Unable to download the plugin with apm

### ISSUE THREAD

**Issue by SatokiOgiso** [argenos/atom-ros#5]
I'm planning to use this plugin for my atom, but the apm command could not download the tarball.

```
$ apm install atom-ros
Installing atom-ros to /home/<username>/.atom/packages ✗
Unable to download https://www.atom.io/api/packages/atom-ros/versions/0.6.0/tarball: 404
```

The repository was updated 6 hours ago and the build seems to be passed.
Although not sure this is the issue of the repo or not, I'd like to report this issue for here.

**Comment by hofbi** [comment]
I have the same issue. Release version in `package.json` is `0.2.0` but maybe there was a typo while uploading to atom package distribution.

**Comment by argenos** [comment]
It seems there were a few errors when updating versions after the last changes, I've published v1.0.0 and hopefully, that fixes the issue.

**Comment by hofbi** [comment]
Confirmed. Could be closed from my side.

**Comment by SatokiOgiso** [comment]
Thank you for quick response, now I could install atom-ros for my atom too.
I'd like to close this issue as now it works.
