### ISSUE TITLE
Fatal error: Can't find ros.h

### ISSUE THREAD

**Issue by ROVguy** [argenos/atom-ros#8]
Hello. 
Not sure if this is actually a bug but after installing atom-ros I get this error when compiling (F5).

 fatal error: ros/ros.h: No such file or directory
#include "ros/ros.h"
^~~
compilation terminated

running catkin_make in terminal works fine.

**Comment by argenos** [comment]
`atom-ros` is only adding grammars, syntax highlighting and snippets, but I haven't really added anything to compile code. Perhaps this is a bug on a different package?

**Comment by ROVguy** [comment]
thanks.
